name: Build Repo
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              node-version: '14'
        - run: npm install -g sperm
        - run: cd emoticons && sperm build cumcord_manifest.json
        - run: mv emoticons/dist/* emoticons/
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: .
