name: Build Repo
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
        - uses: actions/setup-python@v2
          with:
              node-version: '14'
        - run: npm install -g sperm
        - run: cd emoticons && sperm build cumcord_manifest.json
        - run: mv emoticons/dist/* emoticons/
        - run: python build_plugin_index.py emoticons/cumcord_manifest.json emoticons/index.html emoticons
        - run: cd manifesto && sperm build cumcord_manifest.json
        - run: mv manifesto/dist/* manifesto/
        - run: python build_plugin_index.py manifesto/cumcord_manifest.json manifesto/index.html manifesto
        - run: cd helluva && sperm build cumcord_manifest.json
        - run: mv helluva/dist/* helluva/
        - run: python build_plugin_index.py helluva/cumcord_manifest.json helluva/index.html helluva
        - run: cd messagelogger && sperm build cumcord_manifest.json
        - run: mv messagelogger/dist/* messagelogger/
        - run: python build_plugin_index.py messagelogger/cumcord_manifest.json messagelogger/index.html messagelogger
        - run: cd sendev && sperm build cumcord_manifest.json
        - run: mv sendev/dist/* sendev/
        - run: python build_plugin_index.py sendev/cumcord_manifest.json sendev/index.html sendev
        - run: cd messagedeletion && sperm build cumcord_manifest.json
        - run: mv messagedeletion/dist/* messagedeletion/
        - run: python build_plugin_index.py messagedeletion/cumcord_manifest.json messagedeletion/index.html messagedeletion
        - run: cd dieThreadBar && sperm build cumcord_manifest.json
        - run: mv dieThreadBar/dist/* dieThreadBar/
        - run: python build_plugin_index.py dieThreadBar/cumcord_manifest.json dieThreadBar/index.html dieThreadBar
        - run: python build_index.py
        - run: echo "" > .gitignore #let it upload the index files
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: .
